### PR TITLE
Reintroduce analogue clock time icon

### PR DESCRIPTION
**Pull request by tecosaur**
Take 2 of #698, resolving the issue noted in https://github.com/seagle0128/doom-modeline/pull/698#discussion_r1515654446.

Now works on my machine _without_ me loading my config :wink:.

### CODE REVIEW

**Comment by seagle0128** [comment]
Below is the screenshot in my env. The clock looks too small.

image

**Comment by tecosaur** [comment]
Interesting. Seems like the sizing is worse for some reason? It might be the case that the size factor might want to be tweaked depending on the particular graphical/modeline configuration.

Would you like me to expose a clock size customisation variable (and let me know if you'd prefer a `defcustom` or `defvar` if we're just testing)?

**Comment by seagle0128** [comment]
I set `doom-modeline--clock-inverse-size` to 3.0 and it looks great. 

It seems related to the font. If the analogue clock is enabled by default, the users have to set this variable. The experience is not good.

**Comment by tecosaur** [comment]
Ok, so sounds like we should have it off by default.

How about I push these changes?
- Change the default value of `doom-modeline-time-analogue-clock` to `nil`
  (now I look I think I may have missed the other non-segment files when copying over the old state, so I'll correct that along the way)
- Turn `doom-modeline--clock-inverse-size` into a new `defcustom` mentioned in the docstring of `doom-modeline-time-analogue-clock`, possibly make it the non-inverse size, so it's a bit easier to explain. I just did inverse originally so the range of "good numbers" was nicer (3-5) but 0.2-0.4 doesn't seem to bad.

**Comment by seagle0128** [comment]
Sounds good! But I am wondering how to calculate./tweak the ratio?

**Comment by tecosaur** [comment]
Aha! I think I might have figured it out, the problem is that scaling is applied to the SVG based on an `(image-compute-scaling-factor image-scaling-factor)` call that occurs within `create-image`.

I think we might be able to avoid the extra variable after all!

**Comment by tecosaur** [comment]
Let me know how that seems to you.

Since I think this fixes the "weird scaling" issue, I've left `doom-modeline-time-analogue-clock` as `t` by default, but happy to change if you'd prefer.

**Comment by tecosaur** [comment]
I've just made the sizing variable `doom-modeline-time-clock-size`, and made it so it can be set to an integer number of pixels, or a proportion to `doom-modeline-height'.

**Comment by seagle0128** [comment]
Thank you!

**Pull request merged**
