### PR TITLE
Account for removed function eglot--spinner

### PR DESCRIPTION
**Pull request by leungbk**
https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=6b0179f7908c658342d1e642e5444e3d2e1cd997

### CODE REVIEW

**Comment by seagle0128** [comment]
Close #594 .

**Comment by seagle0128** [comment]
Close #594

**Comment by zayfen** [comment]
eglot--spinner is not deleted, just renamed to eglot--progress-reporters

**Comment by leungbk** [comment]
> eglot--spinner is not deleted, just renamed to eglot--progress-reporters

I wouldn't say it was "renamed" in any commonly-understood sense; Stephen Leake removed it three weeks ago because he felt it was useless, then yesterday Danny Freeman added a `progress-reporters` field to the `eglot-lsp-server` struct.

**Comment by seagle0128** [comment]
@leungbk so, maybe `progress-reporters` should be added back?

**Pull request merged**
