### PR TITLE
fix #252

### LINKED ISSUE #252: Eglot changed function name
https://github.com/joaotavora/eglot/commit/146108af7a56bef835556bc32a4dc85e9d83f6c0

Now when I try to start eglot I get error `error in process filter: Symbol’s function definition is void: eglot--current-server`

### PR DESCRIPTION
**Pull request by andreyorst**

### CODE REVIEW

**Comment by seagle0128** [comment]
Why not use `eglot-current-server`?

**Comment by andreyorst** [comment]
I've assumed old code was right, and simply followed the changes in eglot. I don't know what this function does, but it fixes the issue for me.  Should I update the code to the `eglot-current-server`?

**Comment by andreyorst** [comment]
It seem to work too.

**Comment by seagle0128** [comment]
I think `eglot-current-server` should be fine, and the last PR can be reverted, since `eglot` should ensure the correct status via new API `eglot-current-server`, which is used in `eglot--mode-line-format` as well.

I will fix them and close this PR. But please help to test the new version. Thanks!

**Pull request closed without merging**
