### PR TITLE
Add mu4e segment

### PR DESCRIPTION
**Pull request by seanfarley**

### CODE REVIEW

**Comment by seanfarley** [comment]
Here's my second attempt at add the mu4e segment.
screen shot 2019-01-29 at 2 44 04 pm

**Comment by seanfarley** [comment]
Unfortunately, there's a spacing problem I'm having when there are no github notifications:

screen shot 2019-01-29 at 2 44 51 pm

**Comment by seanfarley** [comment]
Should the space between segments be its own segment for easier customization?

**Comment by gregf** [comment]
Sorry to add noise to this issue, but what happened to the envelope that was there in the first iteration? I liked that myself.

**Comment by seanfarley** [comment]
It was never there in first iteration: https://github.com/seagle0128/doom-modeline/pull/100

I find it takes up too much valuable space and that colorization is quicker for me to identify.

**Comment by seagle0128** [comment]
It's much clearer now. It needs spaces in the segment to keep the consistence. I will do some slight changes after the merge. Thank you, @seanfarley !

**Comment by seagle0128** [comment]
I did some changes and fix a several minor issues. Please review the latest codes, @seanfarley . Thanks!

**Comment by seanfarley** [comment]
Thanks for improving it! I'll study what you did!

**Pull request merged**
