### PR TITLE
Change current modeline in a single hook `change-major-mode-hook`

### PR DESCRIPTION
**Pull request by haji-ali**
I want to propose this change so that it is easier to add/remove rules for mode-line changes.

### CODE REVIEW

**Comment by seagle0128** [comment]
Good idea! The only problem is users are unable to set mode-line. It's better make `doom-modeline-set-modeline` as a command.

**Comment by seagle0128** [comment]
It's a good idea. Please proceed.

**Comment by haji-ali** [comment]
If you agree with the approach, I think it's quite ready for merging.

**Comment by seagle0128** [comment]
Thank you! I will do a little refactor work later.

**Comment by seagle0128** [comment]
@haji-ali I use `after-change-major-mode-hook` instead of `change-major-mode-hook` to ensure the major mode is correct.

And I think this method is slower although the alist solution is fine overall. In the hook, the list will be go through every time while opening files.

Thoughts?

**Comment by haji-ali** [comment]
@seagle0128, Agree with `after-change-major-mode-hook` being a better place.

It is technically slower, but the list would not have many entries (currently less than 20). I haven't profiled the function but it shouldn't be noticeable at all, especially compared to other operations that are executed during a major mode change. 
This is a typical solution for similar problems, see for example `file-name-handler-alist`.

**Pull request merged**
