### PR TITLE
Add irc / circe segment

### PR DESCRIPTION
**Pull request by seanfarley**

### CODE REVIEW

**Comment by seanfarley** [comment]
Here are some screenshots.

Main modeline with just a single notification icon:
screen shot 2019-02-03 at 11 09 19 pm

`'special` modeline with all unread buffers listed:
screen shot 2019-02-03 at 11 09 45 pm

**Comment by seanfarley** [comment]
Oh, also, the code I use to change the irc buffer names to icons is:

```lisp

  (defun smf/irc-icons (buffer)
    "Given a BUFFER name, return an icon. Else return buffer."
    (cond
     ((string-match "#mercurial" buffer)
      (all-the-icons-faicon "mercury" :v-adjust .05))
     ((string-match "#bitbucket" buffer)
      (all-the-icons-faicon "bitbucket" :v-adjust .05))
     ((string-match "#octobus-hg" buffer)
      ;; this inserts a custom fonticon, in this case, octobus
      (propertize "\xe900"
                  'face '(:family "smf-custom-icons")
                  'rear-nonsticky t
                  'display '(raise -0.1)
                  'font-lock-ignore t))
     (t buffer)))

  (setq doom-modeline-irc-stylize #'smf/irc-icons)
```

**Comment by seagle0128** [comment]
Thank you.

**Comment by seanfarley** [comment]
Yay!

**Comment by stardiviner** [comment]
Hi, @seanfarley can you add rcirc and ERC support too? I saw source code candidate has only `circe-mode` matched.

**Comment by seanfarley** [comment]
> Hi, @seanfarley can you add rcirc and ERC support too? I saw source code candidate has only `circe-mode` matched.

PRs welcomed!

**Comment by stardiviner** [comment]
I checked out `rcirc` and `ERC`, they does tracking through `tracking-mode`. Seems can't simply add `(derived-mode-p 'rcirc-mode)` here. Huuu

**Comment by seagle0128** [comment]
@seanfarley I did some changes and optimizations for `irc` segment. Please help to test the latest version. PRs are always welcome. Thanks!

@stardiviner Now `erc` is supported.

**Comment by seanfarley** [comment]
Yes, those are some big changes that break most everything for me. Since you merged `irc` and `irc-buffers` segments, there is no longer a way to have a short notification (a simple icon with a number; as seen in my first screenshot) and a long notification (a list of all the buffers; as seen in my second screeshot).

But now @hlissner has already updated doom to remove the `irc-buffers` which I worked hard to get into upstream both here and in doom. So, that's unfortunate. I do wish I had some warning about the upcoming changes; especially since you admit you're not even able to test your own code.

**Pull request merged**
