### PR TITLE
Count flymake diagnostics by severity

### PR DESCRIPTION
**Pull request by vjoki**
Eglot flymake diagnostics were not shown by the checker segment because eglot uses custom error types (eg. `eglot-warning` rather than `warning`) and only the default error types were getting counted.

Since flymake allows backends to define error types I've changed the functions to count based on the severity integers, that increase according to severity, of the default flymake error types.

### CODE REVIEW

**Comment by seagle0128** [comment]
I have to say, it's a bad design of `flymake` and `eglot` :-(
Thank you for the PR.

**Comment by wailo** [comment]
This commits breaks in emacs 26.2. Flymake.el does not contain `flymake--severity`
https://github.com/emacs-mirror/emacs/blob/emacs-26.2/lisp/progmodes/flymake.el

**Comment by vjoki** [comment]
Upon a quick test, replacing the calls to `flymake--severity` with its body seems to work alright for emacs >=26, like so:
```Emacs-Lisp
(flymake--lookup-type-property (flymake--diag-type diag) 'severity
                                 (warning-numeric-level :error))
```
or a newer flymake from ELPA could be used.

**Comment by wailo** [comment]
Thanks for the speed response. Installing a new version from ELPA fixed the issue.

**Comment by seagle0128** [comment]
@vjoki is it possible to be compatible with the built-in fly make are well?

**Comment by vjoki** [comment]
Yes, `flymake--lookup-type-property` exists in the built-in flymake starting from emacs 26, so the function body of `flymake--severity` can be used as is.

**Pull request merged**
